[package]
name = "wasmaker-rust"
version = "0.1.0"
edition = "2024"

[dependencies]




[workspace]
members = [ "crates/generator","crates/rewriter"]


[workspace.dependencies]
wasmparser = "0.239.0"
wasm-encoder = "0.239.0"
anyhow = "1.0.70"
